### ISSUE TITLE
Some rva addresses is not patched

### ISSUE THREAD

**Issue by N1ceL** [jonomango/chum#1]
I understand that you won't be working on this project anymore, but maybe it will help someone in the future. This is an interesting project.

1) For example, there is such a problem in _vcrt_InitializeCriticalSectionEx()->try_get_function() [in CRT with /MT] with the rva address in the current instructions
`49 8B 84 FF ? ? ? ?` `mov rax, rva ????[r15+rdi*8]`
`49 8B 9C F7 ? ? ? ?` `mov rbx, rva ????[r15+rsi*8]`
`4D 8B BC F7 ? ? ? ?` `mov r15, ds:rva ????[r15+rsi*8]`
![s1](https://github.com/jonomango/chum/assets/41979846/35c6499b-47ac-4a32-a480-af1c05f7826b)
Just for the test, this instruction can be caught in this way (this is not the best way, just for test)
`if (instr.mnemonic == ZYDIS_MNEMONIC_MOV && instr.attributes == (ZYDIS_ATTRIB_HAS_MODRM | ZYDIS_ATTRIB_HAS_SIB | ZYDIS_ATTRIB_HAS_REX | ZYDIS_ATTRIB_ACCEPTS_SEGMENT) && instr.length >= 8 && instr.raw.disp.value > 0x1000/*better to do > sec_text_addr + sec_text_size*/)`

2) There is also a problem with rva addresses in .rdata
![image](https://github.com/jonomango/chum/assets/41979846/f54df0c1-90a7-4152-b5e1-826f8a3d246b)
![image](https://github.com/jonomango/chum/assets/41979846/21d8ea8b-6473-44fc-bd70-2f8bed8a7201)

3) I also suspect that there will be problems with some short jmps

**Comment by N1ceL** [comment]
I understand that you won't be working on this project anymore, but maybe it will help someone in the future. This is an interesting project.

There is also a problem with rva addresses in .rdata
![image](https://github.com/jonomango/chum/assets/41979846/f54df0c1-90a7-4152-b5e1-826f8a3d246b)
![image](https://github.com/jonomango/chum/assets/41979846/21d8ea8b-6473-44fc-bd70-2f8bed8a7201)

**Comment by jonomango** [comment]
Thanks for the feedback. For 2, the reason is probably because the disassembler doesn’t recognize that the data is an RVA. This could probably be fixed with some heuristics, but it doesnt really matter in this example since chum doesn’t support exception handling. 

I suspect 1 is related to this as well, but I’ll take a look when I get home.

As for 3, short jumps will get changed to a near jump if the offset can’t fit in the instruction, if that’s what you’re implying. Only 64-bit jmps/calls aren’t supported.

**Comment by jonomango** [comment]
Another note for 3 is that I wrote the relative call/jmp encoding code before Zydis introduced `ZydisEncoderEncodeInstructionAbsolute()`. Switching over to that would make the code a lot cleaner and bug-free (since I'm sure that my implementation has a bunch of bugs!).

**Comment by jonomango** [comment]
@N1ceL Alright I checked it out a bit, and I'm not entirely sure that there is a good solution for this...

This is what the first instruction looks like:
`49 8b 84 ff 70 d1 01 00             mov rax, QWORD PTR [r15+rdi*8+0x1d170]`

As you can see, it is a bit difficult to determine that `0x1d170` is an RVA. One way would be to check for constants in the range of `0 <= x <= image_size`, but this will obviously lead to a huge amount of false positives. A more reliable option would be to scan nearby instructions and look for the image base address... this relies on the fact that RVAs are usually added to the image base.

For example, in the same function just a few instructions before:
`4C 8D 3D 2B DB FF FF                lea     r15, cs:140000000h`

If we could detect the combination of image base + RVA, then maybe this could be reliably detected, but I'm definitely not adding that! 😄

**Comment by N1ceL** [comment]
Thanks for the reply. The solution to this problem is really difficult, but this project is still one of the best on github for mutating instructions with thoughtful logic that other people can take note of. If all the rva addresses were fixed it would be fantastic, but it seems to me that a .map parser is needed for this (.map parser could help in detecting not only such instructions, but also exceptions in .rdata and provide information about the segments of the sections like idata, crt, xdata, edata, pdata and etc. This information would be able to minimize false positives)

**Comment by jonomango** [comment]
> but it seems to me that a .map parser is needed for this (.map parser could help in detecting not only such instructions, but also exceptions in .rdata and provide information about the segments of the sections like idata, crt, xdata, edata, pdata and etc. This information would be able to minimize false positives)

Completely agree. I was planning on adding .map and pdb parsing eventually to the disassembler, but I got bored of this project. The entire project depends on the disassembler to not have any bugs, so when there are bugs, it breaks down completely.
